object Versions {
    const val coreKtx = "1.9.0"
    const val appcombat = "1.7.0"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val activityCompose = "1.7.2"
    const val composeBom = "2023.06.01"
    const val composeUi = "1.5.1"
    const val composeMaterial3 = "1.1.1"
    const val junit = "4.13.2"
    const val androidxJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val material = "1.9.0"
    const val hiltAndroid = "2.55"
    const val hiltAndroidCompiler = "2.55"
    const val hiltCompiler = "1.1.0"
    const val hiltNavigationCompose = "1.2.0"

    const val retrofit = "2.9.0"
    const val okhttp = "4.12.0"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.15.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.12.0"

    const val coroutines = "1.8.1"
    const val splashScreen = "1.0.1"
}